<template>
  <div>
    <UButton
      icon="i-heroicons-pencil"
      size="xs"
      variant="ghost"
    />
    <UButton
      icon="i-heroicons-trash"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-document-duplicate"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-funnel"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-check-circle"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-adjustments-horizontal-solid"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-document-check"
      variant="ghost"
      size="xs"
    />
    <UButton
      icon="i-heroicons-chevron-right-20-solid"
      variant="ghost"
      size="xs"
    />
  </div>
</template>
